version: '3.1'

services:
  redis:
    container_name: redis
    image: redis:6-alpine
    restart: always
    ports:
      - '6379:6379'
    volumes: 
      - cache:/data
    networks:
      - terminus

  # api:
  #   container_name: api
  #   build:
  #     context: .
  #     dockerfile: ./dev.Dockerfile
  #     target: development
  #   volumes:
  #     - ./:/app
  #     - /app/node_modules
  #   depends_on:
  #     - redis
  #   env_file:
  #     - ./.env
  #   ports:
  #     - "3000:3000"  
  #   networks:
  #     - terminus
  #   command: npm run start:dev

volumes:
  cache:

networks:
  terminus:
    driver: bridge