version: '3.1'

services:
  redis:
    container_name: redis
    image: redis:6-alpine
    restart: always
    ports:
      - '6379:6379'
    volumes: 
      - cache:/data
    networks:
      - terminus

  postgres:
    container_name: postgres
    image: postgres:14.5
    restart: always
    ports:
      - '${DATABASE_PORT}:${DATABASE_PORT}'
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
      - PGDATA=/var/lib/postgresql/data
    volumes: 
      - db:/var/lib/postgresql/data
    networks:
      - terminus

  adminer:
    container_name: adminer
    image: adminer:latest
    restart: always
    ports:
      - "8080:8080"
    networks:
      - terminus

volumes:
  cache:
  db:

networks:
  terminus:
    driver: bridge